#!/bin/bash

echo "System Info"
echo "Executed By: $(whoami)"
echo "Hostname: $(hostname)"
echo "Server IP: $(hostname -I | awk '{print $1}') "
echo "Public IP: $(curl -s ifconfig.co)"
echo "Os Type And Version: $(lsb_release -d | cut -f2)"
echo "Kernel Version: $(uname -r)"
echo "Architecture: $(uname -m)"
echo "Virtualization: $(systemd-detect-virt)"
echo "Server time: $(date)"
echo "Timezone: $(timedatectl | grep 'Time zone' | awk '{print $3,$4}')"
echo "Uptime: $(uptime -p)"
echo ""
echo "Resource Usage"
echo "Total Memory: $(free -h | awk  'NR==2 {print $2}')"
echo "Memory Usage: $(free -h | awk 'NR==2 {print $3 "/" $2}')"
echo "Swap Usage: $(free -h | awk 'NR==3 {print $3 "/" $2}')"
echo "Cpu Cores: $(nproc)"

